services:
  tech-backend:
    build: .
    command: ["sleep", "infinity"]
    ports:
      - "8080:8080"
    restart: always
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:${HTTP_PORT}/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
