version: "3.8"
services:
  tech-backend:
    build: .
    env_file: cmd/.env
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    restart: always
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:${HTTP_PORT}/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
