name: Deploy to Remote Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            set -e

            cd /home/lxt/project/tech-backend/cmd
            printf '%s\n' "${{ secrets.ENV_FILE_CONTENT }}" > .env

            echo "[INFO] Changing to project directory..."
            cd /home/lxt/project/tech-backend

            echo "[INFO] Showing .env -- not need pass !!!"
            # cat .env

            echo "[INFO] Pulling latest code..."
            git fetch --all
            git reset --hard origin/main

            echo "[INFO] Building..."
            docker compose build
            echo "[INFO] Starting..."
            docker compose up -d

            echo "[INFO] Checking containers..."
            sleep 3

            if ! docker compose ps | grep "Up"; then
                echo "[ERROR] No running containers detected!"
                docker compose ps
                exit 1
            fi

            echo "[SUCCESS] All containers are up"
